def shift_char(c, shift):
    # Shift character by the given amount, wrapping around the alphabet
    if 'A' <= c <= 'Z':
        return chr((ord(c) - ord('A') + shift) % 26 + ord('A'))
    elif 'a' <= c <= 'z':
        return chr((ord(c) - ord('a') + shift) % 26 + ord('a'))
    else:
        return c  # Non-alphabetical characters are not shifted

def apply_vigenere_like_cipher(text, key):
    key_numbers = [int(k) for k in key]  # Convert each digit in the key to an integer
    result = ""
    for i, c in enumerate(text):
        shift_amount = key_numbers[i % len(key_numbers)]
        result += shift_char(c, shift_amount)
    return result

# Assuming `encoded_text` is your string to decode, and `key` is "66260701"
encoded_text = "LAJFLFEFEFJFHJLHLJHLHLALJHCLCACJLCHLFLCAFHLCFHFCALJLHJLJALHFEJCFJFHCEJAJLJLJFJAJLELFJEHACELCJLFECJLFCHJHEHLJLJCLFLHLJLHLCLHCJHLHLHAJHFHFLJEJHECEJLHJLJHCEHJLJLHJLJLJCJLJHLJLJLHJLHJHLHAEHECLJLHLHLJHLHLHJHLCJHLHCLHEFLJEAEHEHEFHELEHAEHJLHFHJHCEJCLHECLAHLHFELCECFLHJLEFLJLJLHELJHJFHLHLEAHACLCJCHACLHAHAEALACHCLALHAHLAHAEHAEHEAHJLAJHFCHECJCEHECLCHAEAEJCHCLCALALEALELALELELEAEAELELEALELALEHJEJCLELAHALCLCEHFHEHEAJCECFLEHELHAHJEHLHLHALALHLCELELHCAHLCHALELHAEALEAEHLELEHELECELELELELCLELELELELELCLELELELACLEACLCEALEAEAEHLAHEALECELCHECECEAEJEFLECEFELCELELELELELELELECLJECLECELELALCALELELHLECALJELELJLCALCEAELHELELAJACLJEJAJCECEFEHEHECLHLHEHLHELHJLELJLELJLJLJLJCHLCELEALHELEHCECHECEHEHECHLELELJALELEFLAELELECAECLEAECLEJELELHEHECLEHEHECEHEHELCHLJELJLEHEHEHEHEHLHJCFECLECHCFCHCHEFLHFECHFHFHFLHCFHEHFHLJHEHAFHELHFLEFCLEJLHEHECFECHLECHLHECEHECALCHACEAEAHLELAHECJHEHECLHLHLHLEJFLHFCEHLHFJLEFHFLHJFLJLJCHCLJLEJLFLCLCJCJLHEJLJCJLJHJHEAJALELJEHEJALHALHJHELAHLEHLHLHJLHLJLCJCJLCECLHCLCLCECJECEACJELELEFLELAELCHLELHELHFHELECELELELELELCELCELELEHEFELCELEJCELHLELCFLFHLHLJLHLHFCJLHLJLHLHCHCHCHLHCHCHEHCHLHCHLHLHJLJHLJLHEJLJCJLEHLJLCJCJCEHEJECJECHCEJEJHJAHCALCHJCAECJHJHEJCHLCLHLCLCLJCLCJCJCLCLCLCLECLCLCLCLHLCLHCHLHLCHCLCLCJHCHCLCLCLHLCHLCLF"
# encoded_text = ""  # Your encoded text here
key = "66260701"

# Apply the cipher
decoded_text = apply_vigenere_like_cipher(encoded_text, key)

print(decoded_text)
